export const myProjects = [
  {
    projectTitle: "Restaurant",
    category: ["react", "css", "html"],
    imgPath: "./foodera.png",
    link: "https://github.com/midaismael/Restaurant",
    website: "https://midaismael.github.io/Restaurant/",
  },
  {
    projectTitle: "gym landing page",
    category: ["react", "css", "html"],
    imgPath: "./gym-tutorial.png",
    link: "https://github.com/midaismael/gym-tutorial",
    website: "https://midaismael.github.io/gym-tutorial/",
  },
  {
    projectTitle: "news",
    category: ["javascript", "html", "css"],
    imgPath: "./news.png",
    link: "https://github.com/midaismael/news",
    website: "https://midaismael.github.io/news/",
  },
  {
    projectTitle: "emart clothes",
    category: ["react", "html", "css"],
    imgPath: "./clothes-ecomm.png",
    link: "https://github.com/midaismael/emart-clothes",
    website: "https://midaismael.github.io/emart-clothes/",
  },
  {
    projectTitle: "ecommerce phone",
    category: ["react", "html", "css"],
    imgPath: "./phone-eomm.png",
    link: "https://github.com/midaismael/ecommerce-phone",
    website: "https://midaismael.github.io/ecommerce-phone/",
  },
  {
    projectTitle: "coffee landing page",
    category: ["javascript", "html", "css"],
    imgPath: "./coffe-landpage.png",
    link: "https://github.com/midaismael/cafe-landing-page",
    website: "https://midaismael.github.io/cafe-landing-page/",
  },
  {
    projectTitle: "dorsin landing-page",
    category: ["react", "css", "html"],
    imgPath: "./dorsin-landpage.png",
    link: "https://github.com/midaismael/landing-page",
    website: "https://midaismael.github.io/landing-page/",
  },
  {
    projectTitle: "truck store",
    category: ["react", "css", "html"],
    imgPath: "./truck.png",
    link: "https://github.com/midaismael/Truck-store",
    website: "https://midaismael.github.io/Truck-store/",
  },
  {
    projectTitle: "Best eat landing page",
    category: ["react", "css", "html"],
    imgPath: "./fast-food.png",
    link: "https://github.com/midaismael/Best-Eats",
    website: "https://midaismael.github.io/Best-Eats/",
  },

  {
    projectTitle: "weather app",
    category: ["javascript", "html", "css"],
    imgPath: "./weather-app.png",
    link: "https://github.com/midaismael/weather-app",
    website: "",
  },
  {
    projectTitle: "todo list",
    category: ["javascript", "html", "css"],
    imgPath: "./todo-list.png",
    link: "https://github.com/midaismael/todo-list",
    website: "",
  },
  {
    projectTitle: "real state",
    category: ["react", "html", "css"],
    imgPath: "./realstate.png",
    link: "https://github.com/midaismael/RealEstate",
    website: "https://midaismael.github.io/RealEstate/",
  },
];
